apiVersion: v1
kind: Service
metadata:
  name: jmeter-slaves-svc
  namespace: default
  labels:
    jmeter_mode: slave
spec:
  type: NodePort
  ports:
    - port: 1099
      name: first
      targetPort: 1099
    - port: 50000
      name: second
      targetPort: 50000
  selector:
    jmeter_mode: slave          
