apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  namespace: default
  labels:
    jmeter_mode: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
      - name: jmslave
        image: onursungur/jmeter-slaves:latest
        imagePullPolicy: IfNotPresent   
        ports:
        - containerPort: 1099
        - containerPort: 50000     
      imagePullSecrets:
      - name: registrypullsecret  
